# No 'version' tag needed for modern Docker Compose
services:
  mysql-db:
    image: mysql:8.0
    container_name: library-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - library-network

  book-service:
    build: ./book-service
    container_name: book-service
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/library_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SERVER_PORT: 8081
    ports:
      - "18081:8081"  # <- CHANGED FROM 8081:8081 to 18081:8081
    depends_on:
      - mysql-db
    networks:
      - library-network

  member-service:
    build: ./member-service
    container_name: member-service
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/library_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
    networks:
      - library-network

volumes:
  mysql_data:

networks:
  library-network:
    driver: bridge